#!/usr/bin/env bash 
#!/bin/bash

#TODO:
# source, should just export the var here, 
# /Users/pedrolopes/playground/bashscripting/future-os/secret_variables.sh shoule be sourced BY bash, not scripts

source /Users/pedrolopes/playground/bashscripting/secret_variables.sh

action=$1
shift

function usage(){
  echo "  Navigate to URL:"
  echo "    nav ITEM#"
  echo "      Searches for a URL in the todo line and launches a browser."
  echo ""
  exit
}

[ "$action" = "usage" ] && usage

if ! [[ "$1" =~ ^[0-9]+$ ]]; then
    echo "Error! Usage:"
    usage
fi

# changed: echo "[[test:test]]"|grep -E -o "\[\[.+\]\] (allows to catch standard dokuwiki syntax)
URL=$(sed "$1!d" "$TODO_FILE"|grep -E -o "([a-z]*)://[^ ]+|\[\[.+\]\]")
if [ "$URL" = "" ]; then
    LINE=$(sed "$1!d" "$TODO_FILE")
    if [ "$LINE" = "" ]; then
        echo "Error, no item #$1 found!"
    else
        echo "Error, no URL seen in item #$1!"
        echo "$LINE"
    fi
    exit 1
fi
 

# Parse if this is a dokuwiki based link to page (e.g., [[admin:todo]])
if (echo "$URL" | grep -q -E -o "\[\[.+\]\]" && echo 1 >/dev/null 2>&1); then # this is close, do later
  URL="${URL:2:-2}"
  URL="$WIKI_BASEPAGE_URL$URL"
fi

# Trying to be smart...
# on Debian alike:
if $(which x-www-browser >/dev/null 2>&1); then
    exec x-www-browser "$URL"
# with freedesktop.org utils:
elif $(which xdg-open >/dev/null 2>&1); then
    exec xdg-open "$URL"
# if you have git:
elif [ -x /usr/lib/git-core/git-web--browse ]; then
    cd /usr/lib/git-core && ./git-web--browse "$URL"
# last resort, a la mano...
elif $(which firefox >/dev/null 2>&1); then
    exec firefox "$URL"
elif $(which konqueror >/dev/null 2>&1); then
    exec konqueror "$URL"
elif $(which nautilus >/dev/null 2>&1); then
    exec nautilus "$URL"
# Windowsien?
elif [ -x "/cygdrive/c/Program Files/Mozilla Firefox/firefox.exe" ]; then
    exec "/cygdrive/c/Program Files/Mozilla Firefox/firefox.exe" "$URL"
# OS X?
elif [ -x "/usr/bin/open" ]; then
    exec "/usr/bin/open" "$URL"
else
    echo "Sorry I'm giving up, cannot find your browser :-("
    echo "Under cygwin, consider creating a shortcut in the path, like"
    echo "ln -s \"/cygdrive/c/Program Files/Mozilla Firefox/firefox.exe\" /usr/local/bin/firefox"
fi
